server:
  port: 8080
  forward-headers-strategy: native

spring:
  profiles:
    active: local
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/global_ship
    username: admin
    password: admin

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_batch_fetch_size: 1000

security:
  jwt:
    secret: hschurchhschurch
    access-token-ttl-seconds: 3600
    refresh-token-ttl-seconds: 86400

discord:
  error-webhook-url: https://discord.com/api/webhooks/1462367693540823197/OD3poHe0OmJyk0i0yVptQX6NwonRYRmF_rpIZa0xKgRvZIUX1u-NFLYdakWJ4-cmPP5P

aws:
  s3:
    bucket: hsbapch-storage
    region: ap-northeast-2
    access-key: AKIA6HW5JCWPYWBQXTOL
    secret-key: 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