spring:
  application:
    name: hschurch-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    url: jdbc:postgresql://localhost:5432/hschurch
    user: admin
    password: hschurch
  datasource:
    url: jdbc:postgresql://localhost:5432/hschurch
    username: admin
    password: hschurch
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    defer-datasource-initialization: false

logging:
  level:
    com.delivered: INFO